---
title: "Laboratorio 2"
output: html_notebook
---

Datos de los vuelos que partieron en Nueva York en 2013. 

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(nycflights13)

View(flights)

View(airports)

View(planes)

View(airlines)

View(weather)


```

**Inner-join**

1.1. Conectar fligths con planes

```{r}
flights %>%
  inner_join(planes, by = "tailnum")

```
1.2. Conectar fligths con airlines
```{r}
flights %>%
  inner_join(airlines, by = "carrier")
```

1.3. Conectar fligths con airports
```{r}
flights %>%
  inner_join(airports, by = c("origin"="faa")) %>%
  inner_join(airports, by = c( "dest" = "faa"))
```
1.4. Conectar fligths con weather
```{r}
flights %>%
  inner_join(weather, by = c("origin","hour","day","month","year"), suffix=c("_flight","_weather"))
```
**Data manipulation**

2.1. Count

```{r}
flights %>%
  count(year,month,day) %>%
  filter(n > 1000) %>%
  arrange(n)
```
2.2. Seleccion por rango

```{r}

flights_selected <- flights %>%
  dplyr::select(year:day,hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)
  
flights_selected
```
 2.3. Left Join
```{r}
airlines %>%
  left_join(flights_selected, by = "carrier") %>%
  dplyr::select(-origin, -dest) %>%
  mutate(tot_delay = arr_delay + dep_delay)

```
 2.4. Inner Join
 
```{r}

precip_delay <- flights %>%
  inner_join(weather, by = c("origin","hour","day","month","year"), suffix=c("_flight","_weather")) %>%
  group_by(precip) %>%
  summarize(delay = mean(dep_delay, na.rm=TRUE)) %>%
  replace_na(list(delay=0))

precip_delay
  
```
 2.5. Grafico
```{r}

ggplot(precip_delay, aes(x=precip, y=delay)) +
  geom_point()
```
 2.6. Filter
 
```{r}
flights_airports <- flights %>%
  filter(year == 2013) %>%
  filter(month == 5) %>%
  filter(day == 10) %>%
  group_by(dest) %>%
  summarize(delay = mean(arr_delay, na.rm=TRUE)) %>%
  inner_join(airports, by = c("dest"="faa"))

flights_airports
```
 
2.7. Gráfica de puntos
```{r}
ggplot(flights_airports, aes(x=lon, y=lat)) +
  geom_point()
```
2.8. Inner Join
```{r}
flights %>%
  inner_join(planes, by = "tailnum", suffix = c("_flights","_planes")) %>%
  transmute(tailnum, manufacturer, pi = (dep_delay + arr_delay) / air_time)

```

